services:
  - type: web
    name: Chatbot Flow Builder
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: HOST
        value: 0.0.0.0
      - key: RENDER_DATABASE_URL
        sync: false
